.\" Copyright (C), 2014, 2015  Marco Maggi
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH floppy-disk 1 2014-12-23
.SH NAME
floppy-disk \-Floppy disk control
.SH SYNOPSIS
.sp
.nf
\fBfloppy-disk\fR \fImount\fR [OPTIONS]\fR
\fBfloppy-disk\fR \fIumount\fR [OPTIONS]\fR
\fBfloppy-disk\fR \fIshow\fR [OPTIONS]\fR
\fBfloppy-disk\fR \fIhelp\fR
.fi
.sp
.SH DESCRIPTION
.PP
This script performs operations on a floppy disk file system.

.\" ------------------------------------------------------------

.SH SOME  OPTIONS
.PP
\fB\-m\fR \fImount-point\fR,
\fB\-\-mount\-point\fR=\fImount-point\fR
.RS 4
Select \fImount-point\fR as directory under which to mount the floppy
disk file system.  Defaults to \fI/mnt/floppy\fR.
.RE
.PP
\fB\-g\fR \fIgroup-name\fR,
\fB\-\-group\fR=\fIgroup-name\fR
.RS 4
Select \fIgroup-name\fR as user's group under which mount the file
system.  Defaults to the user's group.
.RE

.\" ------------------------------------------------------------

.SH "SEE ALSO"
.PP
The official documentation is distributed in Texinfo format; see the
file \fBmmux-removable-media-utilities\fR.

.\" ------------------------------------------------------------

.SH BUGS
.PP
See the issues at the Github project page:
.PP
.RS 4
\%http://github.com/marcomaggi/mmux-removable-media-utilities/issues
.RE

.\" ------------------------------------------------------------

.SH AUTHOR
Marco Maggi <marco.maggi-ipsu@poste.it>
.\" Local Variables:
.\" fill-column: 72
.\" default-justification: left
.\" End:
