\input texinfo.tex
@c %**start of header
@setfilename mmux-removable-media-utilities.info
@settitle MMUX Removable Media Utilities
@c %**end of header

@include version.texi
@include macros.texi

@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      MMUX Removable Media Utilities

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    MMUX Removable Media Utilities

@c To be used as @value{PACKAGE} whenever we need to include the
@c nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           mmux-removable-media-utilities

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{marco.maggi.ipsu@@poste.it}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2013, 2014, 2015

@c ------------------------------------------------------------

@set GITHUB_URL                 @url{http://github.com/marcomaggi/mmux-removable-media-utilities}
@set DOCUMENTATION_URL          @url{http://marcomaggi.github.com/docs/mmux-removable-media-utilities.html}

@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying
This document describes version @version{} of @value{PACKAGE}, a
distribution of @gnu{} Bash scripts; it provides utilities to handle
removable media like @usb{} pendrives and CD-ROMs.  The package is
distributed under the terms of the @gnu{} General Public License
(@gpl{}).

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the @gnu{} Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with
Invariant Sections being ``@gnu{} Free Documentation License'' and
``@gnu{} General Public License'', no Front--Cover Texts, and no
Back--Cover Texts.  A copy of the license is included in the section
entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @version{}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* mmux-removable-media-utilities: (mmux-removable-media-utilities). @value{TITLE}.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* pendrive::                    Managing @usb{} pendrives.
* cdrom::                       Managing @acronym{CD-ROM}s.
* memory-card::                 Managing @acronym{SD} memory cards.
* floppy-disk::                 Managing floppy disks.

Appendices

* Package License::             GNU General Public License.
* Documentation License::       GNU Free Documentation License.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.
@end menu
@end ifnottex

@c page
@node overview
@chapter Overview of the package


This document describes version @version{} of @value{PACKAGE}, a
distribution of @gnu{} Bash scripts; it provides utilities to handle
removable media like @usb{} pendrives and CD-ROMs.  To use this package,
the following system requirements must be satisfied:

@itemize
@item
The scripts expect the group @code{plugdev} to exist and to allow
members to access removable media; on a Slackware system:

@example
$ grep plugdev /etc/groups
plugdev:x:83:user1,user2
@end example

@noindent
allows @samp{user1} and @samp{user2} to mount and unmount removable
media.

@item
When a removable media is plugged in, for example a @usb{} pendrive, the
device is:

@example
$ ls -l /dev/sdb1
brw-rw---- 1 root plugdev 8, 17 May 24 20:13 /dev/sdb1
@end example

@noindent
device pathnames can be configured with command line options.

@item
The file @file{/etc/fstab} contains the following entry for the mount
point:

@smallexample
/dev/sdb1 /mnt/stick auto defaults,noauto,sync,nosuid,rw,group 0 0
@end smallexample

@noindent
specific options can be customised; the important thing is that
@file{/etc/fstab} has an entry for the mount point.

@item
This package relies on the program @command{sudo} to allow file system
mounting and unmounting to the users of the group @samp{plugdev}; such
policy is configured by the file:

@center @file{/etc/sudoers.d/mmux-removable-media-utilities.conf}

@noindent
which is installed on the system by this package: do not blindly accept
this configuration file!  Take a good look at it and make the necessary
changes for your host.

Remember that such sudoers file must be installed on the system with
octal access permissions @samp{0400}; the installation directory
@file{/etc/sudoers.d} must also have octal access permissions
@samp{0700}.  Such permissions @strong{cannot} be enforced by the
installation infrastructure of this package.

To enable loading of sudoers configuration modules: we have to include
the following line in the file @file{/etc/sudoers}:

@example
#includedir /etc/sudoers.d
@end example
@end itemize

With these system configuration, users that are members of the group
@code{plugdev} can mount a @usb{} pendrive with:

@smallexample
$ pendrive mount
@end smallexample

@noindent
and unmount it with:

@example
$ pendrive umount
@end example

@c page
@node pendrive
@chapter Managing @usb{} pendrives


@usb{} pendrive operations are handled by the command
@command{pendrive}.  Synopsis:

@example
pendrive [action] [options]
@end example

Action commands:

@table @code
@item mount [options] [arguments]
Mount a @usb{} pendrive.

@item umount [options] [arguments]
Unmount a @usb{} pendrive.

@item show [options] [arguments]
Show @usb{} pendrive mount status.

@item sudo-mount [options] [arguments]
Internal action.

@item sudo-umount [options] [arguments]
Internal action.

@item help [options] [arguments]
Print help screen and exit.
@end table

Options:

@table @code
@item -m@var{VALUE}
@itemx --mount-point=@var{VALUE}
Select the mount point (default: @file{/mnt/stick}).

@item -g@var{group-name}
@itemx --group=@var{group-name}
Select @var{group-name} as user's group under which mount the file
system.  Defaults to the user's group.
@end table

@c page
@node cdrom
@chapter Managing @acronym{CD-ROM}s


@acronym{CD-ROM} operations are handled by the command @command{cdrom}.
Synopsis:

@example
cdrom [action] [options]
@end example

Action commands:

@table @code
@item mount [options] [arguments]
Mount a @acronym{CD-ROM}.

@item umount [options] [arguments]
Unmount a @acronym{CD-ROM}.

@item show [options] [arguments]
Show @acronym{CD-ROM} mount status.

@item sudo-mount [options] [arguments]
Internal action.

@item sudo-umount [options] [arguments]
Internal action.

@item help [options] [arguments]
Print help screen and exit.
@end table

Options:

@table @code
@item -m@var{VALUE}
@itemx --mount-point=@var{VALUE}
Select the mount point (default: @file{/mnt/cdrom}).

@item -g@var{group-name}
@itemx --group=@var{group-name}
Select @var{group-name} as user's group under which mount the file
system.  Defaults to the user's group.
@end table

@c page
@node memory-card
@chapter Managing @acronym{SD} memory cards


@acronym{SD} memory card operations are handled by the command
@command{memory-card}.  Synopsis:

@example
memory-card [action] [options]
@end example

Action commands:

@table @code
@item mount [options] [arguments]
Mount a @acronym{SD} memory card.

@item umount [options] [arguments]
Unmount a @acronym{SD} memory card.

@item show [options] [arguments]
Show @acronym{SD} memory card mount status.

@item sudo-mount [options] [arguments]
Internal action.

@item sudo-umount [options] [arguments]
Internal action.

@item help [options] [arguments]
Print help screen and exit.
@end table

Options:

@table @code
@item -m@var{VALUE}
@item --mount-point=@var{VALUE}
Select the mount point (default: @file{/media/memory}).

@item -g@var{group-name}
@itemx --group=@var{group-name}
Select @var{group-name} as user's group under which mount the file
system.  Defaults to the user's group.
@end table

@c page
@node floppy-disk
@chapter Managing floppy disks


The package installs also a @command{floppy-disk} which is currently
undocumented.

@c page
@c ------------------------------------------------------------
@c Appendices.
@c ------------------------------------------------------------

@include gpl-3.0.texi
@include fdl-1.3.texi

@c page
@node references
@appendix Bibliography and references


The documentation of @value{PACKAGE} is available online:

@center @value{DOCUMENTATION_URL}

@noindent
the latest version of this package can be downloaded from:

@center @value{GITHUB_URL}

@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file

